# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://www.erica-sarro.github.io
title: Erica Sarro
email: esarr002@ucr.edu
author: Erica Sarro
description: "Erica's Personal Page"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
# Build sitemap
plugins:
  - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
#  - icon: github
#    title: github
#    url: https://github.com/erica-sarro
  - icon: envelope-o
    title: email
    url: mailto:esarr002@ucr.edu
#  - icon: linkedin
#    title: linkedin
#    url: https://www.linkedin.com/in/erica_sarro/
#  - icon: file-pdf-o
#    title: CV
#    url: img/MyCV.pdf
  - icon: google
    title: google scholar
    url: https://scholar.google.com/citations?user=2SWHvi4AAAAJ&hl=en
  - icon: twitter
    title: twitter
    url: https://twitter.com/erica_sarro

